spring:
  config:
    activate:
      on-profile: "prod"

build:
  info: "v3"
loans:
  message: "Welcome to loans APIs"
  contactDetails:
    name: "Jen Doe"
    email: "jendoe@email.com"
    role: "Business"
  onCallSupport:
    - (111) 12345-1262
    - (222) 12345-1263