server:
  port:
    8082
spring:
  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
build:
  info: "v1"
loans:
  message: "Welcome to loans APIs"
  contactDetails:
    name: "Jen Doe"
    email: "jendoe@email.com"
    role: "Business"
  onCallSupport:
    - (111) 12345-1262
    - (222) 12345-1263