server:
  port:
    8082
spring:
  application:
    name: "loans"

  config:
    import: "optional:configserver:http://localhost:8071/"

  # Temporarily disabling rabbitmq dependencies
  # rabbitmq:
  #   host: "localhost"
  #   port: 5672
  #   username: "guest"
  #   password: "guest"

  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # Eureka server will use this info actuator point to fetch the info detail of the service
  info:
    env:
      enabled: true
  # To expose shutdown endpoint only for demo purpose
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

# To connect to eureka server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
    fetch-registry: true
    register-with-eureka: true

# Information used by info actuator point
info:
  app:
    name: "loans"
    description: "Banking loans application"
    version: "1.0.0"


logging:
  level:
    com:
      banking:
        loans: DEBUG